output_dir: null
seed: 12
methods: 
  - RhoLossRW
method_opt:
  alpha: [0.1, 1.0]
  alpha_scheduler: decrease_linear
  rho: 5.0

rholoss:
  holdout_model_path: exp/reweight_test2/RhoLossRW/best_holdout.pth.tar
  holdout_percentage: .50
  holdout_num_epochs: 30
  holdout_num_steps: 1000000
  holdout_batch_size: 32
  holdout_optimizer: AdamW
  holdout_loss_params: {}
  holdout_optim_params: {lr: 0.001, betas: [0.9, 0.999], momentum: 0.9, weight_decay: 0.01}
  holdout_loss_type: CrossEntropy
  networks:
    type: Small_cnn
    params: 
      m_type: 'Small_cnn'
      num_classes: 10

dataset:
  name: CIFAR10
  root: ./_CIFAR
  include_holdout: True
  # im_size: [32,32]

networks:
  type: ResNet_torchvision
  params: 
    m_type: 'resnet18'
    num_classes: 10

ema_momentum: 0.99

training_opt:
  num_epochs: 50
  # num_steps: 1000000
  num_data_workers: 4
  batch_size: 32
  test_batch_size: 512
  loss_type: CrossEntropy
  loss_params: {reduction: 'none'}
  optimizer: AdamW
  optim_params: {lr: 0.001, betas: [0.9, 0.999], eps: 0.00000001, weight_decay: 0.01, amsgrad: False}
  scheduler: 'constant'
  scheduler_params: {endlr: 0.0001, gamma: 0.1, step_size: 35, milestones: [120, 160]}
logger_opt:
  print_iter: 100

