output_dir: null
seed: 20
methods: 
  - Bayesian
method_opt:
  ratio: 0.1
  balance: False
  ratio_scheduler: constant
  warmup_epochs: 0

bayesian:
  adaptive_alpha: False
  alpha: 0.2
  tau: 4
  prior_precision: 10
  num_effective_data: 200
  laplace_momentum: 0.99
  n_f_samples: 256
  clip_architecture: 'ViT-B/16'

rholoss:
  holdout_model_path: None
  holdout_percentage: .50
  holdout_num_epochs: 25
  holdout_num_steps: 10000
  holdout_batch_size: 32
  holdout_optimizer: SGD
  holdout_loss_params: {}
  holdout_optim_params: {lr: 0.1, momentum: 0.9, weight_decay: 0.0005}
  holdout_loss_type: CrossEntropy
  networks:
    type: ResNet
    params: 
      m_type: 'resnet18'
      num_classes: 10

dataset:
  name: CIFAR10
  root: ./_CIFAR
  include_holdout: True

networks:
  type: ResNet
  params: 
    m_type: 'resnet18'
    num_classes: 10

ema_momentum: 0.99

training_opt:
  num_epochs: 100
  # num_steps: 100000
  num_data_workers: 4
  batch_size: 320
  test_batch_size: 512
  loss_type: CrossEntropy
  loss_params: {}
  optimizer: AdamW
  optim_params: {lr: 0.001, betas: [0.9, 0.999], eps: 0.00000001, weight_decay: 0.01, amsgrad: False}
  scheduler: 'constant'
  scheduler_params: {endlr: 0.0001, gamma: 0.1, step_size: 35, milestones: [120, 160]}
logger_opt:
  print_iter: 100

